service: serverless-ipsum

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs8.10

functions:
  ipsum:
    handler: handler.getIpsum
    events:
      - http:
          path: ipsum
          method: get
          cors: true

custom:
  serverless-offline:
    port: "${env:APP_PORT}"
